### ISSUE TITLE
Protein-to-mRNA ratios

### ISSUE THREAD

**Issue by LivC93** [hexavier/CUSTOM#1]
First of all thank you very much for making this repo available. 

I wanted to ask you something about generating the Protein-to-mRNA ratios. I am trying to find the CSV with the computed labels but I cannot find it anywhere. I found Table EV3 from Eraslan et al. and since it does not need any processing this data should match whatever you used. However, for Jiang et al. (2020) you do talk about some processing (see below). For (2) I was wondering if you can expand a bit just to make sure our data matches and the comparison is justified.

```
(1) proteins with an abundance of 0 were considered as missing values (NA); (2)
protein quantifications were adjusted to have in each tissue the same median than the
overall median; (3) genes with a TPM lower than 10 were taken as non-transcribed (NA).
With that, comparable PTR values between HPA and GTEx are obtained (ED Figure 1A).
```

**Comment by hexavier** [comment]
Hi @LivC93 ,
You are right, in the repo here we directly import the resulting codon weights and ratios generated in our [study](https://www.biorxiv.org/content/10.1101/2022.03.22.485268v1). All raw data, processing and analyses of the article are accessible [here](https://github.com/hexavier/codon_optimization). In particular, you can find and reproduce the processing of data from Jiang et al. (2020) in:
https://github.com/hexavier/codon_optimization/blob/master/2_gtex_computePTR.R
Hope this helps, please let me know if you have further issues!

**Comment by LivC93** [comment]
@hexavier thank you very much for this fast answer. I will give it a go this afternoon. I did find Supplemenary Table 1 [here](https://www.biorxiv.org/content/10.1101/2022.03.22.485268v1.supplementary-material) which should have the data that I need (Tab1 and Tab2). However, I am a bit worried that for the tissues that match between HPA and GTEx the PTR values are very different.

**Comment by LivC93** [comment]
@hexavier  thank you for the fast answer. 

I ran the above mentioned script and then I ran `3-2_ALL_establish_tissuespecificity.R` to get the High/Low PTR genes per tissue. Which I will use for comparison.

**Comment by hexavier** [comment]
Hi @LivC93 ,
Great that it worked. Please note that GTEx proteomics are relative TMT quantifications, while in Eraslan et al. they did absolute label-free iBAQ quantification. Relative values among tissues should match, but absolute quantifications will not.
Best,
