### ISSUE TITLE
Location of  "CUSTOM"

### ISSUE THREAD

**Issue by norisuke1969** [hexavier/CUSTOM#2]
Thank you for sharing this interesting package.

After installing this package at Google Colaboratories and tried to run the basic example, I encountered the error message as below. The installation process looks fine and I could see the "CUSTOM" folder.

Could you please give me some adivce?

Thank you in advance.

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-31-2d1b46478d8c> in <cell line: 2>()
      1 # Import package
----> 2 from CUSTOM import TissueOptimizer
      3 # Start the optimizer
      4 opt = TissueOptimizer("kidney", n_pool=100)
      5 # Optimize the eGFP sequence

ImportError: cannot import name 'TissueOptimizer' from 'CUSTOM' (unknown location)

**Comment by hexavier** [comment]
Hi @norisuke1969 ,
I have never tried it in Google Colab, but it shiuld work the same. Could you maybe try with lower case?
`from custom import TissueOptimizer`
Hope it works,
Xavi

**Comment by norisuke1969** [comment]
Hi Xavi,

Thank you  for your swift reply.
I tried in lower case also. But the result was same.
Should I be in specific folder?

Best regards,

Nori.


2023年10月2日(月) 2:33 Xavier Hernandez-Alias ***@***.***>:

**Comment by hexavier** [comment]
Hi Nori,
I did few changes to the setup.py, and it is working for me (https://colab.research.google.com/drive/12osJy14umhoQvVhStm9-DwBjAhdY9ba-?usp=sharing)
Could you check if it works?
Xavi

**Comment by norisuke1969** [comment]
What!!!

Thank you SO much!! Then what I should do must be git CUSTOM package and
pip install, right?

2023年10月2日(月) 18:54 Xavier Hernandez-Alias ***@***.***>:

**Comment by hexavier** [comment]
No need to do git, just pip.
Best,
Xavi

**Comment by norisuke1969** [comment]
Thanx Understood!

2023年10月2日(月) 23:13 Xavier Hernandez-Alias ***@***.***>:

**Comment by armanoner** [comment]
> Hi Nori, I did few changes to the setup.py, and it is working for me (https://colab.research.google.com/drive/12osJy14umhoQvVhStm9-DwBjAhdY9ba-?usp=sharing) Could you check if it works? Xavi

I recently tried running this colab version. Unfortunately, it fails and prints the following:

> ---------------------------------------------------------------------------
> ModuleNotFoundError                       Traceback (most recent call last)
> [<ipython-input-2-095896f8f1e8>](https://localhost:8080/#) in <cell line: 2>()
>       1 # Import package
> ----> 2 from custom import TissueOptimizer
>       3 # Start the optimizer
>       4 opt = TissueOptimizer("Kidney", n_pool=100)
>       5 # Optimize the eGFP sequence
> 
> 1 frames
> [/usr/local/lib/python3.10/dist-packages/custom/custom.py](https://localhost:8080/#) in <module>
>       7 import numpy as np
>       8 import pandas as pd
> ----> 9 import RNA
>      10 
>      11 # Load data required for optimization
> 
> ModuleNotFoundError: No module named 'RNA'
> 
> ---------------------------------------------------------------------------

I'm not fully clear on the root cause but managed to find a workaround. For anyone running into the same issue, invoking `!pip install viennarna` in addition to `!pip install custom_optimizer` seems to do the trick.

**Comment by norisuke1969** [comment]
Hi Xavier,

Thank you for letting me know.
I also experienced the same error and solved it by installing viennarna
separately.

Anyway will try later today.

Nori.

2024年1月27日(土) 22:33 armanoner ***@***.***>:
