### ISSUE TITLE
Pull values for original sequence

### ISSUE THREAD

**Issue by enc-kcotto** [hexavier/CUSTOM#3]
Hello,

I was curious if there is a way to pull values such as CAI, MFEini, and such from the original starting sequence in order to compare to the codon optimizations that CUSTOM creates.

**Comment by hexavier** [comment]
Hello,
I just committed a small change that should add the original sequence among the newly genarated ones.
Best,
Xavier

**Comment by enc-kcotto** [comment]
Thanks!
